### ISSUE TITLE
How did the receiver distinguish the normal message and the protozoa message

### ISSUE THREAD

**Issue by yafeng-Soong** [dmbb/Protozoa#1]
Sorry to bother you. When I read the paper I saw this sentence "Whenever an encoded frame is reassembled, the downstream hook is executed and extracts the Protozoa message from the EFBP field." in §4.4 last paragraph. However, you did not further explain the problem. I browsed the source code and found that the "/webrtc_patchs/vedio/video_receive_stream.cc" (the function VideoReceiveStream::OnCompleteFrame in line 554) didn't seem to distinguish the normal message and the protozoa message. It just passed all the messages to the hook and replaced all the messages with keyframe/deltaframe.
So you can tell me how did the receiver distinguish the normal message and the protozoa message? Thanks for helping

**Comment by dmbb** [comment]
Hi!

Effectively, the receiver will always replace all received frames with a pre-recorded delta/keyframe. The data inside modified frames (whether they encapsulate an IP packet or not) is processed by the server component (`https://github.com/dmbb/Protozoa/blob/master/protozoa/src/ProtozoaServerThread.cpp`. This component will know what to do if there is an IP packet present in a modified frame. Keep in mind that all frames (whether they encapsulate IP packets or not) do include a bitstring with some metadata which is overwritten on top of usual video frames' data.

**Comment by yafeng-Soong** [comment]
Thanks for patiently answering my questions! Respect! @dmbb

**Comment by dmbb** [comment]
Hope that helps! I'm closing this topic, but feel free to ask any additional questions :)
